// === VIK Mock Data ===

export const systemMetrics = {
  gpu: {
    name: 'NVIDIA Quadro P5000',
    vramTotal: 16384,
    vramUsed: 11264,
    temperature: 72,
    utilization: 78,
    powerDraw: 145,
    powerLimit: 180,
  },
  cpu: {
    name: '2x Intel Xeon E5-2667 v2',
    cores: 16,
    threads: 32,
    utilization: 34,
    temperature: 58,
    frequency: 3.3,
  },
  ram: {
    total: 131072,
    used: 48640,
    cached: 24576,
  },
  uptime: '14d 7h 32m',
  hostname: 'vik-proliant-ml350',
  os: 'Ubuntu 24.04 LTS',
};

export const gpuHistory = Array.from({ length: 30 }, (_, i) => ({
  time: `${i}m`,
  vram: 8000 + Math.random() * 5000,
  util: 50 + Math.random() * 40,
  temp: 60 + Math.random() * 15,
}));

export const cpuHistory = Array.from({ length: 30 }, (_, i) => ({
  time: `${i}m`,
  usage: 20 + Math.random() * 40,
  temp: 45 + Math.random() * 20,
}));

export const mcpServers = [
  {
    id: 'orchestrator',
    name: 'Mózg Operacyjny',
    type: 'Orkiestrator',
    language: 'Python 3.12',
    status: 'running',
    port: 2000,
    description: 'Główny silnik LangChain z logiką agentową',
    model: 'bielik-11b-v3.0-instruct:Q6_K',
    uptime: '14d 7h',
    requests: 12847,
    errors: 3,
  },
  {
    id: 'system-manager',
    name: 'Zarządca Systemu',
    type: 'Serwer MCP',
    language: 'Rust',
    status: 'running',
    port: 3001,
    description: 'Telemetria serwera, nvidia-smi, zarządzanie zasobami',
    uptime: '14d 7h',
    requests: 45210,
    errors: 0,
  },
  {
    id: 'web-navigator',
    name: 'Nawigator Internetowy',
    type: 'Serwer MCP',
    language: 'Python + Playwright',
    status: 'running',
    port: 3002,
    description: 'Autonomiczna nawigacja Chromium headless',
    uptime: '14d 6h',
    requests: 892,
    errors: 12,
  },
  {
    id: 'stt-engine',
    name: 'Silnik STT',
    type: 'Moduł Mowy',
    language: 'C++ (Whisper.cpp)',
    status: 'running',
    port: 3003,
    description: 'Transkrypcja offline — model small, polski',
    uptime: '14d 5h',
    requests: 1543,
    errors: 7,
  },
  {
    id: 'tts-engine',
    name: 'Silnik TTS',
    type: 'Moduł Mowy',
    language: 'Python (Piper)',
    status: 'idle',
    port: 3004,
    description: 'Synteza mowy CPU, strumień WAV/MP3',
    uptime: '14d 5h',
    requests: 987,
    errors: 1,
  },
  {
    id: 'tool-sandbox',
    name: 'Piaskownica Narzędzi',
    type: 'Sandbox',
    language: 'Docker + Python',
    status: 'standby',
    port: 3005,
    description: 'Izolowany kontener do dynamicznego generowania narzędzi',
    uptime: '14d 7h',
    requests: 45,
    errors: 2,
  },
  {
    id: 'telegram-bot',
    name: 'Bot Telegram',
    type: 'Interfejs',
    language: 'Python',
    status: 'running',
    port: null,
    description: 'python-telegram-bot — interfejs mobilny',
    uptime: '14d 7h',
    requests: 3210,
    errors: 0,
  },
  {
    id: 'ollama',
    name: 'Serwer Ollama',
    type: 'LLM Runtime',
    language: 'Go',
    status: 'running',
    port: 11434,
    description: 'Serwer modeli GGUF — Q6_K / Q4_K_M',
    uptime: '14d 7h',
    requests: 15890,
    errors: 5,
  },
];

export const ollamaModels = [
  {
    name: 'bielik-11b-v3.0-instruct:Q6_K',
    size: '8.6 GB',
    family: 'Bielik',
    params: '11B',
    quantization: 'Q6_K',
    role: 'Główny rdzeń procesowy (PL)',
    loaded: true,
    vramUsage: 7800,
  },
  {
    name: 'deepseek-r1:14b-qwen-distill',
    size: '9.2 GB',
    family: 'DeepSeek',
    params: '14B',
    quantization: 'Q4_K_M',
    role: 'Reasoning & Tool Creation',
    loaded: false,
    vramUsage: 8400,
  },
  {
    name: 'llava:13b-v1.6-Q4_K_M',
    size: '7.4 GB',
    family: 'LLaVA',
    params: '13B',
    quantization: 'Q4_K_M',
    role: 'Model wizyjny (OCR, analiza)',
    loaded: false,
    vramUsage: 7200,
  },
  {
    name: 'nomic-embed-text:v1.5',
    size: '274 MB',
    family: 'Nomic',
    params: '137M',
    quantization: 'FP16',
    role: 'Embeddingi RAG',
    loaded: true,
    vramUsage: 350,
  },
];

export const chatMessages = [
  {
    id: 1,
    role: 'system',
    content: 'VIK zainicjalizowany. Bielik-11B gotowy do pracy. Wszystkie systemy operacyjne.',
    timestamp: '09:00:01',
  },
  {
    id: 2,
    role: 'user',
    content: 'Dzień dobry VIK. Jaki jest aktualny stan zasobów serwera?',
    timestamp: '09:15:22',
  },
  {
    id: 3,
    role: 'assistant',
    content: 'Dzień dobry! Sprawdzam stan systemu...\n\n**GPU Quadro P5000:**\n- VRAM: 11.0/16.0 GB (68.8%)\n- Temperatura: 72°C\n- Wykorzystanie: 78%\n\n**CPU 2x Xeon:**\n- Użycie: 34%\n- Temperatura: 58°C\n\n**RAM:** 47.5/128 GB (37.1%)\n\nWszystkie serwisy MCP działają poprawnie. Serwer Ollama obsługuje model Bielik-11B z kwantyzacją Q6_K.',
    timestamp: '09:15:24',
    model: 'bielik-11b-v3.0-instruct:Q6_K',
    tools_used: ['system-manager'],
  },
  {
    id: 4,
    role: 'user',
    content: 'Sprawdź ostatnie wiadomości na Hacker News i podsumuj top 3.',
    timestamp: '09:20:15',
  },
  {
    id: 5,
    role: 'assistant',
    content: 'Uruchamiam Nawigator Internetowy...\n\n**Top 3 z Hacker News:**\n\n1. **"Open Source LLM Benchmark 2025"** (523 pkt)\nNowa platforma porównawcza modeli — DeepSeek R1 prowadzi w kategorii reasoning.\n\n2. **"Rust Memory Safety Report"** (412 pkt)\nAnaliza bezpieczeństwa pamięci w projektach Linux Kernel napisanych w Rust.\n\n3. **"MCP Protocol v2.0 Released"** (389 pkt)\nAnthropologic opublikował nową wersję Model Context Protocol z obsługą streamingu.',
    timestamp: '09:20:28',
    model: 'bielik-11b-v3.0-instruct:Q6_K',
    tools_used: ['web-navigator'],
  },
];

export const logEntries = [
  { id: 1, timestamp: '2025-01-15 09:00:01', level: 'INFO', service: 'orchestrator', message: 'System VIK zainicjalizowany pomyślnie' },
  { id: 2, timestamp: '2025-01-15 09:00:02', level: 'INFO', service: 'ollama', message: 'Model bielik-11b-v3.0-instruct:Q6_K załadowany do VRAM (7.8 GB)' },
  { id: 3, timestamp: '2025-01-15 09:00:03', level: 'INFO', service: 'ollama', message: 'Model nomic-embed-text:v1.5 załadowany (350 MB)' },
  { id: 4, timestamp: '2025-01-15 09:00:04', level: 'INFO', service: 'system-manager', message: 'Serwer MCP Rust uruchomiony na porcie 3001' },
  { id: 5, timestamp: '2025-01-15 09:00:05', level: 'INFO', service: 'web-navigator', message: 'Playwright Chromium headless gotowy' },
  { id: 6, timestamp: '2025-01-15 09:00:06', level: 'INFO', service: 'stt-engine', message: 'Whisper.cpp small model załadowany (GPU Pascal, 780 MB VRAM)' },
  { id: 7, timestamp: '2025-01-15 09:00:07', level: 'INFO', service: 'tts-engine', message: 'Piper TTS uruchomiony w trybie CPU (24 wątków)' },
  { id: 8, timestamp: '2025-01-15 09:00:08', level: 'INFO', service: 'telegram-bot', message: 'Bot Telegram połączony i nasłuchuje' },
  { id: 9, timestamp: '2025-01-15 09:01:12', level: 'DEBUG', service: 'system-manager', message: 'GPU temp: 68°C | VRAM: 8150/16384 MB | Util: 42%' },
  { id: 10, timestamp: '2025-01-15 09:05:00', level: 'INFO', service: 'orchestrator', message: 'Celery worker uruchomiony — Redis broker aktywny' },
  { id: 11, timestamp: '2025-01-15 09:15:22', level: 'INFO', service: 'orchestrator', message: 'Zapytanie użytkownika: "stan zasobów serwera"' },
  { id: 12, timestamp: '2025-01-15 09:15:23', level: 'DEBUG', service: 'orchestrator', message: 'Router: przypisano narzędzie system-manager' },
  { id: 13, timestamp: '2025-01-15 09:15:24', level: 'INFO', service: 'system-manager', message: 'Telemetria zebrana: GPU/CPU/RAM — odpowiedź OK' },
  { id: 14, timestamp: '2025-01-15 09:20:15', level: 'INFO', service: 'orchestrator', message: 'Zapytanie użytkownika: "wiadomości Hacker News"' },
  { id: 15, timestamp: '2025-01-15 09:20:16', level: 'DEBUG', service: 'orchestrator', message: 'Router: przypisano narzędzie web-navigator' },
  { id: 16, timestamp: '2025-01-15 09:20:25', level: 'INFO', service: 'web-navigator', message: 'Pobranie DOM: https://news.ycombinator.com — konwersja Markdown OK' },
  { id: 17, timestamp: '2025-01-15 09:20:28', level: 'INFO', service: 'orchestrator', message: 'Odpowiedź wygenerowana — 3 artykuły podsumowane' },
  { id: 18, timestamp: '2025-01-15 09:25:00', level: 'WARNING', service: 'ollama', message: 'VRAM usage: 11264/16384 MB (68.8%) — próg ostrzeżenia' },
  { id: 19, timestamp: '2025-01-15 09:30:12', level: 'ERROR', service: 'web-navigator', message: 'Timeout: strona nie odpowiada po 30s — https://example-slow.com' },
  { id: 20, timestamp: '2025-01-15 09:30:13', level: 'INFO', service: 'orchestrator', message: 'Retry web-navigator — próba 2/3' },
];

export const sandboxTools = [
  {
    id: 'weather-api',
    name: 'weather_get_forecast',
    description: 'Pobiera prognozę pogody z OpenWeather API',
    status: 'active',
    created: '2025-01-10',
    language: 'Python',
    tests: { passed: 5, failed: 0 },
    schema: '{"location": "string", "days": "int"}',
  },
  {
    id: 'stock-api',
    name: 'stock_get_price',
    description: 'Sprawdza cenę akcji przez Yahoo Finance API',
    status: 'active',
    created: '2025-01-12',
    language: 'Python',
    tests: { passed: 8, failed: 1 },
    schema: '{"ticker": "string", "period": "string"}',
  },
  {
    id: 'email-sender',
    name: 'email_send',
    description: 'Wysyła e-mail przez SMTP z szablonami',
    status: 'testing',
    created: '2025-01-14',
    language: 'Python',
    tests: { passed: 2, failed: 3 },
    schema: '{"to": "string", "subject": "string", "body": "string"}',
  },
  {
    id: 'pdf-parser',
    name: 'pdf_extract_text',
    description: 'Ekstrakcja tekstu i tabel z plików PDF',
    status: 'building',
    created: '2025-01-15',
    language: 'Python',
    tests: { passed: 0, failed: 0 },
    schema: '{"file_path": "string", "pages": "list[int]"}',
  },
];

export const dockerContainers = [
  { name: 'vik-postgres', status: 'running', image: 'postgres:16', port: '5432' },
  { name: 'vik-qdrant', status: 'running', image: 'qdrant/qdrant:v1.12', port: '6333' },
  { name: 'vik-redis', status: 'running', image: 'redis:7-alpine', port: '6379' },
  { name: 'vik-celery-worker', status: 'running', image: 'vik/celery:latest', port: '-' },
  { name: 'vik-sandbox-runtime', status: 'idle', image: 'vik/sandbox:latest', port: '3005' },
];
