// === VIK Mock Data — dane zastępcze gdy backend/Ollama niedostępne ===

export const systemMetricsFallback = {
  gpu: {
    name: 'Brak GPU (dane zastępcze)',
    vramTotal: 0,
    vramUsed: 0,
    temperature: 0,
    utilization: 0,
    powerDraw: 0,
    powerLimit: 0,
    available: false,
  },
  cpu: {
    name: 'Nieznany CPU',
    cores: 1,
    threads: 1,
    utilization: 0,
    temperature: 0,
    frequency: 0,
  },
  ram: {
    total: 0,
    used: 0,
    cached: 0,
  },
  uptime: 'N/A',
  hostname: 'localhost',
  os: 'Nieznany',
};

export const mcpServers = [
  {
    id: 'orchestrator',
    name: 'Mózg Operacyjny',
    type: 'Orkiestrator',
    language: 'Python 3.12',
    status: 'running',
    port: 2000,
    description: 'Główny silnik LangChain z logiką agentową',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'system-manager',
    name: 'Zarządca Systemu',
    type: 'Serwer MCP',
    language: 'Rust',
    status: 'running',
    port: 3001,
    description: 'Telemetria serwera, nvidia-smi, zarządzanie zasobami',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'web-navigator',
    name: 'Nawigator Internetowy',
    type: 'Serwer MCP',
    language: 'Python + Playwright',
    status: 'running',
    port: 3002,
    description: 'Autonomiczna nawigacja Chromium headless',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'stt-engine',
    name: 'Silnik STT',
    type: 'Moduł Mowy',
    language: 'C++ (Whisper.cpp)',
    status: 'standby',
    port: 3003,
    description: 'Transkrypcja offline — model small, polski',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'tts-engine',
    name: 'Silnik TTS',
    type: 'Moduł Mowy',
    language: 'Python (Piper)',
    status: 'standby',
    port: 3004,
    description: 'Synteza mowy CPU, strumień WAV/MP3',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'tool-sandbox',
    name: 'Piaskownica Narzędzi',
    type: 'Sandbox',
    language: 'Docker + Python',
    status: 'standby',
    port: 3005,
    description: 'Izolowany kontener do dynamicznego generowania narzędzi',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'telegram-bot',
    name: 'Bot Telegram',
    type: 'Interfejs',
    language: 'Python',
    status: 'standby',
    port: null,
    description: 'python-telegram-bot — interfejs mobilny',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
  {
    id: 'ollama',
    name: 'Serwer Ollama',
    type: 'LLM Runtime',
    language: 'Go',
    status: 'standby',
    port: 11434,
    description: 'Serwer modeli GGUF',
    uptime: 'N/A',
    requests: 0,
    errors: 0,
  },
];

export const logEntries = [
  { id: 1, timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19), level: 'INFO', service: 'backend', message: 'VIK Backend uruchomiony' },
  { id: 2, timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19), level: 'INFO', service: 'ollama', message: 'Sprawdzanie połączenia z Ollama...' },
  { id: 3, timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19), level: 'INFO', service: 'system', message: 'Zbieranie metryk systemowych' },
  { id: 4, timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19), level: 'DEBUG', service: 'api', message: 'Endpointy API zarejestrowane' },
  { id: 5, timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19), level: 'INFO', service: 'frontend', message: 'Dashboard załadowany' },
];


export const sandboxTools = [
  {
    id: 'weather-api',
    name: 'weather_get_forecast',
    description: 'Pobiera prognozę pogody z OpenWeather API',
    status: 'active',
    created: '2025-01-10',
    language: 'Python',
    tests: { passed: 5, failed: 0 },
    schema: '{"location": "string", "days": "int"}',
  },
  {
    id: 'stock-api',
    name: 'stock_get_price',
    description: 'Sprawdza cenę akcji przez Yahoo Finance API',
    status: 'active',
    created: '2025-01-12',
    language: 'Python',
    tests: { passed: 8, failed: 1 },
    schema: '{"ticker": "string", "period": "string"}',
  },
  {
    id: 'email-sender',
    name: 'email_send',
    description: 'Wysyła e-mail przez SMTP z szablonami',
    status: 'testing',
    created: '2025-01-14',
    language: 'Python',
    tests: { passed: 2, failed: 3 },
    schema: '{"to": "string", "subject": "string", "body": "string"}',
  },
  {
    id: 'pdf-parser',
    name: 'pdf_extract_text',
    description: 'Ekstrakcja tekstu i tabel z plików PDF',
    status: 'building',
    created: '2025-01-15',
    language: 'Python',
    tests: { passed: 0, failed: 0 },
    schema: '{"file_path": "string", "pages": "list[int]"}',
  },
];

export const dockerContainers = [
  { name: 'vik-postgres', status: 'running', image: 'postgres:16', port: '5432' },
  { name: 'vik-qdrant', status: 'running', image: 'qdrant/qdrant:v1.12', port: '6333' },
  { name: 'vik-redis', status: 'running', image: 'redis:7-alpine', port: '6379' },
  { name: 'vik-celery-worker', status: 'running', image: 'vik/celery:latest', port: '-' },
  { name: 'vik-sandbox-runtime', status: 'idle', image: 'vik/sandbox:latest', port: '3005' },
];
